### ISSUE TITLE
[FEAT] Allow to style BPMN Elements

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#13]
`bpmn-visualization` already provides a CSS API but it requires the CSS styles are defined in the html page. Is this convenient for the R integration? the R package may not let R user to modify the underlying html page.

We may need `bpmn-visualization` to provide a new API that let style specific BPMN elements: https://github.com/process-analytics/bpmn-visualization-js/issues/1030. This feature is available as of bpmn-visualization@0.33.0 which is bundled in bpmnVisualizationR 0.4.0.

**Comment by assynour** [comment]
@tbouffard @csouchet This is among the priority features for our demos
