### ISSUE TITLE
[INFRA] Simplify the way we publish release announces on twitter and discord

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#130]
Currently (in v0.2.1), the announce to twitter and discord must be done manually.
The maintainers documentation provides a template, but this is painful and error prone

We could setup a workflow to publish on our name. It will be run on demand (workflow_dispatch) with some inputs:
- the version that has been released
- the "short description" to display in the announce

**Notes**: we have the same needs for the `bpmn-visualization` TypeScript library, see https://github.com/process-analytics/bpmn-visualization-js/issues/2341

**Comment by csouchet** [comment]
See the tests done with https://github.com/marketplace/actions/actions-status-discord & https://github.com/marketplace/actions/tweet-action on https://github.com/process-analytics/github-actions-playground/pull/212.
