### ISSUE TITLE
[INFRA] The release workflow fails to disable the branch protection rules

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#153]
Seen while attempting to release version 0.2.2.
Workaround: follow the manual procedure

Workflow runs: https://github.com/process-analytics/bpmn-visualization-R/actions/runs/3533388259
3 attempts, all failed. The last one was run in debug mode, no additional information

Action configuration
```
Run benjefferies/branch-protection-bot@1.0.7
  with:
    access_token: ***
    enforce_admins: true
    branch: main
    retries: 5
```

Error stack
```
Getting branch protection settings for process-analytics/bpmn-visualization-R
Traceback (most recent call last):
  File "/bin/run.py", line 83, in <module>
    toggle_enforce_admin(p.parse_args())
  File "/bin/run.py", line 22, in toggle_enforce_admin
    protection = get_protection(access_token, branch_name, owner, repo_name)
  File "/bin/run.py", line 61, in get_protection
    protection = branch.protection()
  File "/pyroot/lib/python3.7/site-packages/github3/decorators.py", line 31, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/pyroot/lib/python3.7/site-packages/github3/repos/branch.py", line 73, in protection
    json = self._json(resp, 200)
  File "/pyroot/lib/python3.7/site-packages/github3/models.py", line 157, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
```

**Comment by csouchet** [comment]
To test, I created a [main](https://github.com/process-analytics/github-actions-playground/tree/main) branch on https://github.com/process-analytics/github-actions-playground, with a rule like the master `branch`, and I change the default branch with the `main` branch.

**Comment by csouchet** [comment]
To test, I deleted the rule of the master `branch` on https://github.com/process-analytics/github-actions-playground.

I ran the workflow on the `main` branch: https://github.com/process-analytics/github-actions-playground/actions/runs/3764905611. The job works fine ✅ 

![image](https://user-images.githubusercontent.com/4921914/209318175-d9a73ffb-a321-4a15-bee1-524d50770ca0.png)

**Comment by csouchet** [comment]
On https://github.com/process-analytics/bpmn-visualization-R, the rule **Do not allow bypassing the above settings** was missing.

**Comment by csouchet** [comment]
To test, I added the rules **Require a pull request before merging**, **Require approvals**, **Require status checks to pass before merging** and **Require branches to be up to date before merging** on the `main` branch of https://github.com/process-analytics/github-actions-playground.

I ran the workflow on the `main` branch: https://github.com/process-analytics/github-actions-playground/actions/runs/3765137238/jobs/6400302241. The job works fine ✅

**Comment by csouchet** [comment]
To test, I update the version of **Ubuntu** (ubuntu-22.04) on the `main` branch, like https://github.com/process-analytics/bpmn-visualization-R.

I ran the workflow on the `main` branch: https://github.com/process-analytics/github-actions-playground/actions/runs/3765998102. The job works fine ✅

**Comment by csouchet** [comment]
To test, I deleted the `master` branch on origin.

I ran the workflow on the main branch: https://github.com/process-analytics/github-actions-playground/actions/runs/3766043340. The job works fine ✅

**Comment by csouchet** [comment]
The access token used for benjefferies/branch-protection-bot@1.0.7 has the same right in https://github.com/process-analytics/github-actions-playground and process-analytics/bpmn-visualization-R.

**Comment by csouchet** [comment]
I wonder if the problem is the capitalization in the repository name: bpmn-visualization-R.

**Comment by csouchet** [comment]
When I tried to get the protection of the `main` branch via Rest API, following https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#get-branch-protection, I had the following error:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/4921914/209349560-70215273-d97a-4169-836d-e1aaf3fb658e.png">

Note: I generated a new token with the same rights as `GH_RELEASE_TOKEN`, with access on https://github.com/process-analytics/bpmn-visualization-R.

**Comment by csouchet** [comment]
I tried to recreate the `main` rule, like it was.

❌ I always had the same error.

**Comment by csouchet** [comment]
I checked the rules protection from https://github.com/process-analytics/bpmn-visualization-js and https://github.com/process-analytics/bpmn-visualization-R. They are the same, but on https://github.com/process-analytics/bpmn-visualization-js, it's on the `master` branch.

**Comment by csouchet** [comment]
✅ When I do the same test with the `main` branch of https://github.com/process-analytics/github-actions-playground and the same token, I had the following result:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4921914/209360615-88002912-36c2-4719-a9b4-20b00adcf172.png">

**Comment by csouchet** [comment]
I renamed the `main` branch to `master` on https://github.com/process-analytics/bpmn-visualization-R.

❌ I always had the same error.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/4921914/209361064-43bc45e4-1971-4a5f-bad3-3d79accb1e5f.png">

**Comment by csouchet** [comment]
I think the problem come from the REST API of GitHub.
I found this repository https://github.com/github/rest-api-description. I don't know if we should open an issue here.

**Comment by csouchet** [comment]
When I checked with the GitHub Rest API the list of the branches, I have the `main` branch, and it's protected.

https://api.github.com/repos/process-analytics/bpmn-visualization-R/branches
<img width="644" alt="image" src="https://user-images.githubusercontent.com/4921914/209363106-ff016d56-263d-429e-b328-e53cf1dbe478.png">

**Comment by csouchet** [comment]
I found the problem 🎉 

On https://github.com/process-analytics/bpmn-visualization-R, the owner of the token doesn't have the right **Admin**.

After changing it, it works fine 💃🏻🕺🏻👯‍♀️ 
<img width="918" alt="image" src="https://user-images.githubusercontent.com/4921914/209363589-77411ccb-4d11-4027-982d-8f5f882896e0.png">

**Comment by tbouffard** [comment]
✔️ the owner of the token now has the Admin permissions.

I suggest we keep this issue open until we validate that the workflow now correctly works.

**Comment by tbouffard** [comment]
The workflow runs successfully to create the 0.3.0 release.
See https://github.com/process-analytics/bpmn-visualization-R/actions/runs/3872636874/jobs/6601712109
