### ISSUE TITLE
[BUG] Some overlays may not be added when one in the list refers to an non existing bpmn element

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-R#44]
**Describe the bug**
If we try to add an overlay to a non existing bpmn element, an error is displayed in the browser console and subsequent overlays are not added.

**To Reproduce**
Add several overlays, with one overlay relating to a non existing bpmn element id. The overlays in the list declared after the special one are not displayed.
```r
bpmn_file <- system.file("examples/Email_Voting.bpmn", package = "bpmnVisualization")
# generate error in js binding file
overlays <- list(
  bpmnVisualization::create_overlay("does_not_exist_bpmn_element_id_1", "42"),
  bpmnVisualization::create_overlay("sub_process_1", "110") # id of an existing bpmn element, overlay not added
)
bpmnVisualization::display(bpmn_file, overlays)
```

console error
```
Uncaught TypeError: Cannot read property 'bpmnSemantic' of undefined
    at x.overlays.x.overlays.map.overlay (bpmnVisualization.js:33)
    at Array.map (<anonymous>)
    at Object.renderValue (bpmnVisualization.js:29)
    at Object.renderValue (htmlwidgets.js:886)
    at htmlwidgets.js:653
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
    at htmlwidgets.js:576
    at Array.forEach (<anonymous>)
    at forEach (htmlwidgets.js:55)
```

JS binding code
```javascript
const elementsByIds = bpmnVisualization.bpmnElementsRegistry.getElementsByIds(overlay.elementId);
if (elementsByIds) {
  // this is line 33
  const overlayConfig = elementsByIds[0].bpmnSemantic.isShape ? {
```

**Expected behavior**
The overlay for existing bpmn elements should be added.
For non existing elements, we shouldn't have error. We may log a warning.

**Additional context**
commit: 600286d4ef1986b20e554d3b01893782f7a5e06b
bpmn-visualization: 0.19.0

It seems that in the `elementsByIds` array returned by `bpmn-visualization`, we have `undefined` elements.
Notice that the TS lib implementation is supposed to avoid `undefined` in the array: https://github.com/process-analytics/bpmn-visualization-js/blob/v0.19.0/src/component/registry/bpmn-elements-registry.ts#L75
We already have tests for this use case and more are added without showing any issue (https://github.com/process-analytics/bpmn-visualization-js/pull/1507)

The `getElementsByIds` function is only needed here because we need to know if we have a shape or an edge to choose the arbitrary position of the overlay. This may not be needed anymore when implementing #15 if we let the user choose the overlay position or if we use the TS lib overlay default position.

**Comment by csouchet** [comment]
It seems that `bpmnVisualization.bpmnElementsRegistry.getElementsByIds(overlay.elementId)` returns an array with undefined value.
We should open a bug in https://github.com/process-analytics/bpmn-visualization-js.

**Comment by tbouffard** [comment]
The issue is in the js binding of the R package

When requesting a unknown bpmn element id, `bpmnElementsRegistry.getElementsByIds` returns an empty array. So there is no element at index `0` in the array, so `elementsByIds[0]` returns `undefined`
**Possible fix**: also check that the array has elements
