### ISSUE TITLE
[TEST] Add automatic tests

### ISSUE THREAD

**Issue by csouchet** [process-analytics/bpmn-visualization-R#6]
Also update the GitHub workflow introduced by #25 
See https://r-pkgs.org/tests.html and https://r-pkgs.org/r-cmd-check.html#tests-1

For coverage, see
- https://www.rostrum.blog/2020/08/09/ghactions-pkgs/#example-r2eng-package
- https://github.com/matt-dray/r2eng/blob/master/.github/workflows/test-coverage.yaml

**Comment by ColinFay** [comment]
Happy to try this one for Hacktoberfest

**Comment by csouchet** [comment]
We are happy that you are interested 🙂 
We assigned you this issue.
